# Generated by Django 4.2.4 on 2023-08-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project',
            name='executor',
        ),
        migrations.DeleteModel(
            name='HistoricalProject',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
